services:
  # ? Service Principal de l'app
  bsn-main:
    container_name: bsn-main
    build:
      context: ./main
      dockerfile: Dockerfile.main
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./main:/app
      - /app/node_modules
    depends_on:
      - bsn-api-users
      - bsn-auth
      - bsn-permission
      - bsn-acl

  # ? µService d'accès unique à la bdd users !
  bsn-api-users:
    container_name: bsn-api-users
    build:
      context: ./api-users
      dockerfile: Dockerfile.apiUsers
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./api-users:/app
      - /app/node_modules
    depends_on:
      - bsn-db-users

  # ? µService d'authentication
  bsn-auth:
    container_name: bsn-auth
    build:
      context: ./auth-service
      dockerfile: Dockerfile.auth
    ports:
      - "3002:3000"
    env_file:
      - .env
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - bsn-api-users

  # ? µService permission / authorization
  bsn-permission:
    container_name: bsn-permission
    build:
      context: ./permission-service
      dockerfile: Dockerfile.authz
    ports:
      - "3003:3000"
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./permission-service:/app
    depends_on:
      - bsn-auth

  # ? µService ACL
  bsn-acl:
    container_name: bsn-acl
    build:
      context: ./acl-service
      dockerfile: Dockerfile.acl
    ports:
      - "3004:3000"
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./acl-service:/app
    depends_on:
      - bsn-permission

  # ? µService d'accès unique à la bdd posts !
  bsn-api-posts:
    container_name: bsn-api-posts
    build:
      context: ./api-posts
      dockerfile: Dockerfile.apiPosts
    ports:
      - "3005:3000"
    env_file:
      - .env
    volumes:
      - ./api-posts:/app
      - /app/node_modules
    depends_on:
      - bsn-db-posts

  # ? bdd users mongoDB
  bsn-db-users:
    container_name: bsn-db-users
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env.users
    volumes:
      - ./data/seedingUsers.js:/docker-entrypoint-initdb.d/seedingUsers.js
      - /data/bd_users

  # ? bdd posts mongoDB
  bsn-db-posts:
    container_name: bsn-db-posts
    image: mongo:latest
    ports:
      - "27018:27017"
    restart: always
    env_file:
      - .env.posts
    volumes:
      - ./data/seedingPosts.js:/docker-entrypoint-initdb.d/seedingPosts.js
      - /data/bd_posts